services:
  traefik:
    image: traefik:v2.9.6
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
    ports:
      - "88:80"
      - "8088:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  labcaller-api:
    build:
      context: ../labcaller-api
      dockerfile: Dockerfile.dev
    environment:
      - DB_HOST=labcaller-db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=psql
      - DB_NAME=postgres
      - DB_PREFIX=postgresql
      - KEYCLOAK_UI_ID=${KEYCLOAK_UI_ID}
      - KEYCLOAK_API_ID=${KEYCLOAK_API_ID}
      - KEYCLOAK_API_SECRET=${KEYCLOAK_API_SECRET}
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - KEYCLOAK_URL=${KEYCLOAK_URL}
      - S3_URL=${S3_URL}
      - S3_BUCKET_ID=${S3_BUCKET_ID}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - APP_NAME=${APP_NAME}
      - DEPLOYMENT=local
      - KUBECONFIG=/root/.kube/config
      - KUBE_NAMESPACE=runai-enac-it-ejthomas
    ports:
      - 3005:3000
    depends_on:
        - labcaller-db
    volumes:
      - ../labcaller-api/src:/app/src
      - labcaller-api-build-data:/app/target  # Store builds in docker volume
      - ../labcaller-api/Cargo.toml:/app/Cargo.toml
      - ../labcaller-api//Cargo.lock:/app/Cargo.lock
      - ../kubeconfig:/root/.kube/config
    labels:
      - "traefik.http.routers.labcaller-api.rule=Host(`labcaller`) && PathPrefix(`/api`)"
      - "traefik.http.services.labcaller-api.loadbalancer.server.port=3000"

  labcaller:
    build:
      context: .
      dockerfile: Dockerfile.dev
    labels:
      - "traefik.http.routers.labcaller.rule=Host(`labcaller`)"
      - "traefik.http.services.labcaller.loadbalancer.server.port=5173"
    volumes:
      - ../labcaller:/app

  labcaller-db:
    image: postgres:17.0
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=psql
      - POSTGRES_DB=postgres
    ports:
      - 5443:5432
    volumes:
      - labcaller-db-data:/var/lib/postgresql/data

  labcaller-tus:
    image:  tusproject/tusd:latest
    environment:
      - AWS_ACCESS_KEY_ID=${S3_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${S3_SECRET_KEY}
      - AWS_REGION=us-east-1
    command: -s3-bucket ${S3_BUCKET_ID} -s3-endpoint ${S3_URL} -s3-object-prefix labcaller-local -behind-proxy -port 8080 -hooks-http http://labcaller-api:3000/tus/hooks -hooks-http-forward-headers Authorization
    volumes:
      - labcaller-tus-data:/data
    labels:
      - "traefik.http.routers.labcaller-tus.rule=Host(`labcaller`) && PathPrefix(`/files`)"
      - "traefik.http.services.labcaller-tus.loadbalancer.server.port=8080"

volumes:
  labcaller-db-data:
  labcaller-api-build-data:
  labcaller-tus-data: